'use client';

import React from 'react';
import { motion } from 'motion/react';
import { EXPERIENCES } from '@/src/data/experience';
import { Briefcase, Calendar, MapPin, CheckCircle2 } from 'lucide-react';

export default function ExperienceSection() {
  return <section id="experience" className="py-16 sm:py-20 px-4 sm:px-6 max-w-6xl mx-auto scroll-mt-24"><div className="text-center max-w-2xl mx-auto mb-12"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-white/[0.06] border border-white/10 text-neutral-300 text-xs font-semibold uppercase tracking-wider mb-3"><Briefcase className="w-3.5 h-3.5" />Timeline & Milestones</div><h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-3">Professional Experience</h2><p className="text-sm text-neutral-400">A track record of building Minecraft systems, AI tooling, and full-stack web platforms.</p></div><div className="space-y-6">{EXPERIENCES.map((exp, idx) => <motion.div key={exp.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: idx * 0.1 }} className="glass-panel hover-surface p-6 sm:p-8 rounded-2xl relative overflow-hidden"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4"><div><span className="inline-block px-2 py-0.5 rounded-md bg-white/[0.07] text-neutral-200 text-xs font-semibold mb-2">{exp.badge}</span><h3 className="text-xl font-bold text-white tracking-tight">{exp.role}</h3><p className="text-xs sm:text-sm font-medium text-neutral-400">{exp.organization}</p></div><div className="flex flex-col sm:items-end text-xs text-neutral-400 gap-1 mt-1 sm:mt-0"><div className="flex items-center gap-1.5 text-neutral-300"><Calendar className="w-3.5 h-3.5" /><span>{exp.period}</span></div><div className="flex items-center gap-1.5 text-neutral-500"><MapPin className="w-3.5 h-3.5" /><span>{exp.location}</span></div></div></div><p className="text-xs sm:text-sm text-neutral-300 leading-relaxed mb-5">{exp.description.en}</p><div className="space-y-2 mb-6">{exp.highlights.map((h) => <div key={h} className="flex items-start gap-2.5 text-xs text-neutral-400"><CheckCircle2 className="w-3.5 h-3.5 text-neutral-300 shrink-0 mt-0.5" /><span>{h}</span></div>)}</div><div className="flex flex-wrap gap-1.5 pt-4 border-t border-white/5">{exp.technologies.map((t) => <span key={t} className="text-[11px] font-medium px-2.5 py-1 rounded-lg bg-white/5 text-neutral-300 border border-white/5">{t}</span>)}</div></motion.div>)}</div></section>;
}
